/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatprogramapplet;

import java.awt.event.ActionEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author James
 */
public class ChatProgramApplet extends javax.swing.JApplet{

    private Connection connection;

    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {

                public void run() {
                    initComponents();
                    launchconnection();
                    //serverMessagesArea.setText("ay");
                }
            });
        } catch (Exception ex) {
            serverMessagesArea.setText(ex.toString());
        }
    }


    private void launchconnection() {
        connection = new Connection(this, serverMessagesArea, messageArea, responseArea);
        connection.start();
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        
        

        connectButton = new javax.swing.JButton();
        serverMessagesFieldLabel = new javax.swing.JLabel();
        responseAreaLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rPane = new javax.swing.JScrollPane();
        serverMessagesArea = new javax.swing.JTextArea();
        responseArea = new javax.swing.JTextArea();
        messageArea = new JTextArea(5, 50);
        messageArea.setWrapStyleWord(true);
        messageArea.setLineWrap(true);
        disconnectButton = new javax.swing.JButton();
        sendButton = new javax.swing.JButton();
        
        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                sendButtonActionPerformed(e);
            }
        });

        connectButton.setText("Connect");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });
        
        responseAreaLabel.setText("Server Responses");
        responseArea.setColumns(20);
        responseArea.setRows(2);

        serverMessagesFieldLabel.setText("Messages");

        serverMessagesArea.setColumns(20);
        serverMessagesArea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        serverMessagesArea.setRows(5);
        jScrollPane1.setViewportView(serverMessagesArea);
        rPane.setViewportView(responseArea);

        disconnectButton.setText("Disconnect");
        disconnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rPane, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .addComponent(serverMessagesFieldLabel)
                    .addComponent(messageArea)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(connectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addComponent(disconnectButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addComponent(sendButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rPane, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serverMessagesFieldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageArea)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disconnectButton)
                    .addComponent(connectButton)
                    .addComponent(sendButton))
                .addGap(211, 211, 211))
        );
    }// </editor-fold>                        

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        if (!connection.isConnected()) {
            JFrame frame = new JFrame();
            this.setHandle(JOptionPane.showInputDialog(frame,
                                                    "Enter Your Nickname: ",
                                                    "Name Entry",
                                                    JOptionPane.PLAIN_MESSAGE));
            connection.connectToServer();
        }
}                                             

    private void disconnectButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        if (connection.isConnected()) {
            connection.disconnectFromServer();
        }
}
    
    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if(connection.isConnected()){
            connection.sendToServer();
        }
    }

    public void stop() {
        disconnectButtonActionPerformed(null);
    }
    
    public String getHandle() {
        return this.handle;
    }
    
    public void setHandle(String handle) {
        this.handle = handle;
    }


    // Variables declaration - do not modify                     
    private javax.swing.JButton connectButton;
    private javax.swing.JButton disconnectButton;
    private javax.swing.JButton sendButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane rPane;
    private javax.swing.JTextArea serverMessagesArea;
    private javax.swing.JTextArea messageArea;
    private javax.swing.JTextArea responseArea;
    private javax.swing.JLabel serverMessagesFieldLabel;
    private javax.swing.JLabel responseAreaLabel;
    private String handle;
    // End of variables declaration                   
    
}
